from pathlib import Path

DEFAULT_REPO_DIR = Path.cwd() / "repo"
MAX_FILE_CHARS = 4000
MAX_SNIPPETS = 10
MAX_SNIPPET_CHARS = 500
MAX_TOOL_RESULT_CHARS = 8000
MESSAGE_WINDOW_BLOCKS = 8
REFLECT_MAX_OUTPUT_CHARS = 1000
TEST_OUTPUT_TAIL_CHARS = 2000
IGNORE_DIRS = {".git", "__pycache__", "node_modules", "venv", ".venv", "dist", "build", ".env"}
SUMMARY_TRIGGER_MESSAGES = 50
RECENT_MESSAGES_KEEP = 5

TOOL_MAX_RETRIES = 2
TOOL_RETRY_INITIAL_DELAY = 1.0
TOOL_RETRY_BACKOFF_FACTOR = 2.0
TOOL_RETRY_EXCEPTIONS = (ConnectionError, TimeoutError, OSError)

MODEL_MAX_RETRIES = 2
MODEL_RETRY_INITIAL_DELAY = 2.0
MODEL_RETRY_BACKOFF_FACTOR = 2.0

TEST_PYTEST_TIMEOUT = 120
TEST_ENTRY_POINT_TIMEOUT = 45
TEST_OUTPUT_MAX_CHARS = 4000
TESTABLE_EXTENSIONS = {".py", ".js", ".ts", ".jsx", ".tsx", ".go", ".rs", ".java", ".kt"}
DOCS_CONFIG_EXTENSIONS = {".md", ".mdx", ".txt", ".yml", ".yaml", ".json", ".toml", ".ini", ".cfg", ".env"}
